brew 'ack'
brew 'awscli'
brew 'ctags'
brew 'direnv'
brew 'ghq'
brew 'gist'
brew 'git'
brew 'go'
brew 'gpg2'
brew 'grc'
brew 'hub'
brew 'jq'
brew 'lesspipe'
brew 'nkf'
brew 'nodebrew'
brew 'peco'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rbenv'
brew 'rbenv-ctags'
brew 'rbenv-default-gems'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'tig', args: ['with-docs']
brew 'tmux'
brew 'vim', args: ['with-lua', 'with-luajit', 'with-python3']
brew 'zsh', args: ['disble-etcdir']

tap 'caskroom/cask'

cask_args appdir: '/Applications'

# cask update
cask '1password'
cask 'alfred'
cask 'android-file-transfer'
cask 'blisk'
cask 'cmd-eikana'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'gyazo'
cask 'hammerspoon'
cask 'iterm2'
cask 'kindle'
cask 'kitematic'
cask 'sequel-pro'
cask 'skitch'

# vim: filetype=ruby
