brew 'tig'
brew 'tmux'
brew 'ghq'
brew 'jq'

# Zsh
brew 'starship'
brew 'fzf'
brew 'asdf'
brew 'zoxide'

# Neovim
brew 'neovim'
brew 'fd'
cask 'font-hack-nerd-font'
brew 'ripgrep'
brew 'tree-sitter-cli'
