brew 'awscli'
brew 'direnv'
brew 'ghq'
brew 'git'
brew 'jq'
brew 'peco'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'asdf'

# For asdf-golang
brew 'coreutils'
# For asdf-nodejs
brew 'gpg'
brew 'gawk'

tap 'neovim/neovim'
brew 'neovim'

cask_args appdir: '/Applications'
tap 'homebrew/cask'

cask 'alfred'
cask 'caffeine'
cask 'dash'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'skitch'
cask 'slack'
cask 'visual-studio-code'
