brew 'direnv'
brew 'gh'
brew 'ghq'
brew 'git'
brew 'jq'
brew 'peco'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'asdf'
brew 'pam-reattach'

# For asdf-golang
brew 'coreutils'
# For asdf-nodejs
brew 'gpg'
brew 'gawk'

brew 'neovim'

cask_args appdir: '/Applications'
tap 'homebrew/cask'

cask 'alfred'
cask 'caffeine'
cask 'dash'
cask 'docker'
cask 'hammerspoon'
cask 'visual-studio-code'
