brew 'direnv'
brew 'gh'
brew 'ghq'
brew 'git'
brew 'jq'
brew 'peco'
brew 'tig'
brew 'tmux'
brew 'tmuxinator'
brew 'tree'
brew 'asdf'
brew 'pam-reattach'

# Zsh
brew 'starship'

# Neovim
brew 'neovim'
brew 'fd'
brew 'font-hack-nerd-font'
brew 'ripgrep'
brew 'tree-sitter-cli'

# For asdf-golang
brew 'coreutils'
# For asdf-nodejs
brew 'gpg'
brew 'gawk'

cask_args appdir: '/Applications'

cask 'alfred'
cask 'ghostty'
cask 'hammerspoon'
cask 'visual-studio-code'
