#!/bin/bash
# git hook to run a command after `git pull` if a specified file was changed.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  if [ -f $1 ] ; then
    echo "$changed_files" | grep --quiet "$1" && eval "$2"
  fi
}

.git/hooks/ctags >/dev/null 2>&1 &

check_run .gitmodules  "git submodule init && git submodule update"
check_run Gemfile.lock "bundle install"
check_run package.json "npm install"
