#!/bin/bash
# git hook to run a command after `git pull` if a specified file was changed.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Example usage
[ -f Gemfile.lock ] && check_run Gemfile.lock "bundle install"
[ -f package.json ] && check_run package.json "npm install"

.git/hooks/ctags >/dev/null 2>&1 &
