#!/bin/bash
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
while read local_ref local_sha remote_ref remote_sha
do
  if [[ "${remote_ref##refs/heads/}" = "master" ]]
  then
    # Allows us to read user input below, assigns stdin to keyboard
    exec < /dev/tty

    while read -p "Are you sure to push to master branch? [y/n] " answer
    do
      case $answer in
      y)
        echo pushing to master...
        break
        ;;
      n)
        exit 1
        ;;
      *)
        echo "Please answer y or n"
        ;;
      esac
    done
  fi
done
