#!/bin/zsh

local candidates selected_dir

# Unique array
typeset -Ua candidates

candidates=($(ls -d $HOME/src/*) $(ghq list --full-path))

selected_dir=$(echo $candidates | perl -pe 's/ /\n/g' | percol --query "$LBUFFER")
if [ -n "$selected_dir" ] ; then
    BUFFER="cd $selected_dir"
    zle accept-line
fi
zle clear-screen
